### PR TITLE
Memory card flip game

### PR DESCRIPTION
**Pull request by MAYURIKOTHARI299**

### CODE REVIEW

**Review by KhushbooGupta2111 — CHANGES_REQUESTED** [review]
@MAYURIKOTHARI299 please make another folder named of your project inside frontend and then add these files inside the folder.
Please check how others have done it.

**Comment by MAYURIKOTHARI299** [comment]
@KhushbooGupta2111 Done the required changes .

**Comment by MAYURIKOTHARI299** [comment]
@KhushbooGupta2111 Done the required changes .

**Comment by KhushbooGupta2111** [comment]
Yes perfect

**Review by KhushbooGupta2111 — APPROVED** [review]

**Review by hiferli — APPROVED** [review]

**Review by hiferli — APPROVED** [review]

**Pull request merged**
