### PR TITLE
added news_monkey a react based news website  for the issue no#88

### PR DESCRIPTION
**Pull request by mpatwa98**
…mpatwa98
issues no. #88 
I added a folder named news_monkey in Web Developement/Frontend
please check it and merge it if you fiind it good.

### CODE REVIEW

**Review by hiferli — CHANGES_REQUESTED** [review]
Please add a README file along with this project to describe the project a bit.
Moreover, please ensure that your API key is not publically visible. Add the file with the API key in the .gitignore file

**Review by KhushbooGupta2111 — CHANGES_REQUESTED** [review]
Please make the changes suggested

**Comment by mpatwa98** [comment]
I have made the required changes please check it.

**Comment by mpatwa98** [comment]
thanks.....

**Pull request merged**
