### PR TITLE
Dice game by Ankur-Sh

### PR DESCRIPTION
**Pull request by Ankur-Sh**
refresh to play

### CODE REVIEW

**Comment by hiferli** [comment]
Hey Ankur.
Please shift your project to the Web Developmet/Front End directory
Since all the frontend projects are merged in the specified folder

**Comment by hiferli** [comment]
Since @shivdeep0712 has already added a dice game, please make sure that the Directory names don't collide with the one present

**Comment by Ankur-Sh** [comment]
ok

**Comment by Ankur-Sh** [comment]
i have sent another PR

**Comment by hiferli** [comment]
Closing this PR Since you created a new PR to address the changes

**Pull request closed without merging**
