### PR TITLE
PersonalPortfolio

### PR DESCRIPTION
**Pull request by s-k-jha**

### CODE REVIEW

**Comment by s-k-jha** [comment]
image

**Review by hiferli — DISMISSED** [review]

**Comment by hiferli** [comment]
Hello SK
The whole application is perfectly fine
However it's not a good practice to add your personal information in an open source project.
Can you please change your personal information with dummy values.

**Comment by hiferli** [comment]
For example:
- You can change your personal image with a dummy image available online
- You can change your name with a sample name
- You can replace any personal description with lorem text
- You can replace any social media links with dummy links or (xyz.com/sample)

**Review by hiferli — CHANGES_REQUESTED** [review]
Mentioned

**Comment by s-k-jha** [comment]
sure I will change the personal information @hiferli and then create a pull request again
By the way thanks😀

**Comment by s-k-jha** [comment]
> sure I will change the personal information @hiferli and then create a pull request again By the way thanks😀

image
@hiferli

**Comment by s-k-jha** [comment]
> For example:
> 
> * You can change your personal image with a dummy image available online
> * You can change your name with a sample name
> * You can replace any personal description with lorem text
> * You can replace any social media links with dummy links or (xyz.com/sample)

I have changed all these information now please check once again and accept it! @hiferli

**Review by hiferli — APPROVED** [review]

**Comment by hiferli** [comment]
Great :)
Thank you for making these changes.

**Pull request merged**
