### PR TITLE
Weather app modification

### PR DESCRIPTION
**Pull request by rakeshrk6**
Implemented jQuery, modified UI, added pictorial view(some images that represented the specific weather condition)

### CODE REVIEW

**Review by KhushbooGupta2111 — COMMENTED** [review]
@hiferli, the API key is visible, are there any issues? Shall we request to move it to git.ignore?

**Comment by hiferli** [comment]
Yepp an open API key is always an issue.
Someone can use this key to make calls and thereafter it may add up to the cost.
Hence it's always better to hide the keys in .gitignore

**Comment by hiferli** [comment]
Please add the API key in .gitignore files to avoid any such issue

**Review by hiferli — APPROVED** [review]

**Comment by hiferli** [comment]
Thank you for making these changes

**Pull request merged**
