### PR TITLE
Android Project Added (GitCheatFinder)

### PR DESCRIPTION
**Pull request by aritra-tech**
**Description**
Git Cheat Finder is an Android Application 📲 to easily find the right Git Commands that you want to use. It is made using Kotlin and REST API

182035975-f56345de-6fe7-4047-9a22-375d55690048

Issue No #45

### CODE REVIEW

**Comment by hiferli** [comment]
I believe there is a project more than just the README related to the project.
Was this project actually initiated with git before too?
Since I am only able to see a submodule with the name "GitCheats" and not a proper directory.
Please let us know in case of any issue related to PRs

**Comment by aritra-tech** [comment]
> I believe there is a project more than just the README related to the project. Was this project actually initiated with git before too? Since I am able to see a submodule with the name "GitCheats" and not a proper directory (Apart from the README). Please let us know in case of any issue related to PRs

Ooo yes that's my fault 
Sorry for that

**Comment by hiferli** [comment]
No issues.
You can create another PR correcting the issue

**Comment by aritra-tech** [comment]
> No issues. You can create another PR correcting the issue

Ok ok

**Pull request merged**
